build:
  version: "2.0"
loans:
  message: "Welcome to EazyBank loans related PROD APIs FILE-SYSTEM"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@eazybank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384

