build:
  version: "2.0"
loans:
  message: "Welcome to EazyBank loans related QA APIs FILE-SYSTEM"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371
